# if there are bugs then use node:16-alpine instead of node:alpine
FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .
RUN chown -R node:node /app/node_modules

CMD ["npm", "run", "start"]
